server:
  port: 8080
  servlet:
    context-path: /blog-press

application:
  name: Blog Press
  version: 1.0.0-SNAPSHOT

spring:
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.50.214:5432/blogpress
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true

      stat-view-servlet:
        #配置监控页面访问登录名称
        login-username: admin
        #配置监控页面访问密码
        login-password: admin
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          # 打开记录慢SQL功能
          log-slow-sql: true
          # 慢SQL阈值
          slow-sql-millis: 1000
      filters: stat,wall
      aop-patterns: com.blogpress

  # 国际化配置
  messages:
    basename: i18n.Messages
  application:
    name: Blog Press

  # Redis配置
  redis:
    host: 192.168.50.214
    port: 6379
    database: 0
    password: 123456

  # Session存储方式配置
  session:
    store-type: redis

  elasticsearch:
    rest:
      uris: 192.168.50.214:9200

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_logic_deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.blogpress.**.entity
  configuration:
    map-underscore-to-camel-case: true

# PageHelper配置
pagehelper:
  auto-dialect: true
